THREAD:
    NETWORK_SETUP_COMMANDS:
      - "ot-ctl dataset init new"
      - "ot-ctl dataset commit active"
      - "ot-ctl ifconfig up"
      - "ot-ctl thread start"
      - "ot-ctl state"
      - "ot-ctl netdata show"
      - "ot-ctl ipaddr"
      - "ot-ctl dataset active -x"
      - "ot-ctl udp open"
      - "ot-ctl udp bind :: 45"

    NODES:
      - name: rpi_camera
        mac: E4:5F:01:1E:0A:34
        server_url: http://192.168.1.13:5000/
